# Generated by Django 6.0.3 on 2026-03-24 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0002_banco_mostrar_en_carga_masiva_banco_notas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('PERSONAL', 'Bicicleta Personal (Deuda Propia)'), ('TERCEROS', 'Bicicleta de Terceros (Préstamo a otro)')], max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costo_mensual_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Costo mensual o interés (%)', max_digits=5)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tarjeta_asociada', models.ForeignKey(blank=True, help_text='Tarjeta de la que se sacó el préstamo (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_asociados', to='configuracion.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préstamo (Bicicleta)',
                'verbose_name_plural': 'Préstamos (Bicicletas)',
                'ordering': ['-created_at'],
            },
        ),
    ]
