# Generated by Django 5.1.7 on 2026-03-16 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, 'Month 1'), (2, 'Month 2'), (3, 'Month 3'), (4, 'Month 4'), (5, 'Month 5'), (6, 'Month 6'), (7, 'Month 7'), (8, 'Month 8'), (9, 'Month 9'), (10, 'Month 10'), (11, 'Month 11'), (12, 'Month 12')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='periodo_activo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Active Period',
                'verbose_name_plural': 'Active Periods',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='America/Santiago', max_length=50)),
                ('default_currency', models.CharField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar'), ('UF', 'Unidad de Fomento')], default='CLP', max_length=3)),
                ('dia_recordatorio', models.IntegerField(default=1, help_text='Día del mes para recordatorio de alimentación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_defecto_salario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_con_salario_defecto', to='configuracion.banco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], max_length=10)),
                ('content_type', models.CharField(help_text='Model name that was changed', max_length=100)),
                ('object_id', models.IntegerField(help_text='ID of the changed object')),
                ('field_name', models.CharField(blank=True, help_text='Specific field changed', max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_auditados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Change',
                'verbose_name_plural': 'Audit Changes',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_audito_user_id_5f5ad4_idx'), models.Index(fields=['content_type', 'object_id'], name='core_audito_content_f45fac_idx')],
            },
        ),
    ]
