# Generated by Django 5.1.7 on 2026-03-16 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bancos/')),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_recordatorio_alimentacion', models.IntegerField(default=1, help_text='Day of month for data entry reminder (1-28)')),
                ('mostrar_modo_lectura', models.BooleanField(default=False, help_text='Show read-only mode by default')),
                ('actualizar_tc_automatico', models.BooleanField(default=True, help_text='Auto-update exchange rates daily')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banco_defecto_salario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='configuracion.banco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_general', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración General',
                'verbose_name_plural': 'Configuraciones Generales',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('TDC', 'Tarjeta de Crédito'), ('LINEA_CREDITO', 'Línea de Crédito'), ('CUENTA', 'Cuenta Corriente'), ('COBRO', 'Cobro/Cargo'), ('OTRO', 'Otro')], max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='configuracion.banco')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['banco__orden', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('uf', models.DecimalField(decimal_places=4, help_text='Valor de la UF en CLP', max_digits=10)),
                ('dolar', models.DecimalField(decimal_places=4, help_text='Valor del USD en CLP', max_digits=10)),
                ('fuente', models.CharField(default='mindicador.cl', help_text='Source of the data (mindicador.cl, manual, etc)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cambio',
                'verbose_name_plural': 'Tipos de Cambio',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='configuraci_fecha_9ac32f_idx')],
                'unique_together': {('fecha', 'fuente')},
            },
        ),
    ]
