# Generated by Django 6.0.3 on 2026-03-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='mostrar_en_carga_masiva',
            field=models.BooleanField(default=True, help_text='Mostrar inputs de esta entidad en la carga masiva (ej. comisiones)'),
        ),
        migrations.AddField(
            model_name='banco',
            name='notas',
            field=models.TextField(blank=True, help_text='Datos de transferencia e información relevante'),
        ),
    ]
