# Generated by Django 6.0.3 on 2026-03-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_banco_mostrar_en_carga_masiva_banco_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiene_cupo_usd',
            field=models.BooleanField(default=False, help_text='Si es Tarjeta de Crédito, indica si maneja un cupo en dólares separado'),
        ),
    ]
