# Generated by Django 6.0.3 on 2026-03-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_producto_tiene_cupo_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('TDC', 'Tarjeta de Crédito'), ('LINEA_CREDITO', 'Línea de Crédito'), ('CREDITO_CONSUMO', 'Crédito de Consumo'), ('CUENTA', 'Cuenta Corriente'), ('COBRO_BANCO', 'Cobro de Banco'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
