# Generated by Django 6.0.3 on 2026-03-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0004_alter_producto_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("TDC", "Tarjeta de Crédito"),
                    ("LINEA_CREDITO", "Línea de Crédito"),
                    ("CREDITO_CONSUMO", "Crédito de Consumo"),
                    ("CREDITO_HIPOTECARIO", "Crédito Hipotecario"),
                    ("CUENTA", "Cuenta Corriente"),
                    ("COBRO_BANCO", "Cobro de Banco"),
                    ("OTRO", "Otro"),
                ],
                max_length=20,
            ),
        ),
    ]
