# Generated by Django 6.0.3 on 2026-03-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_alter_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='contabilizar',
            field=models.BooleanField(default=True, help_text='Si es Falso, los gastos en este producto no suman al egreso total del mes'),
        ),
        migrations.AddField(
            model_name='producto',
            name='dia_cobro',
            field=models.IntegerField(blank=True, help_text='Día del mes (1-31) en que vence/se cobra', null=True),
        ),
    ]
