from django.urls import path
from . import views
from configuracion.views import update_rates, take_snapshot

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('gastos/', views.gastos_table, name='gastos-table'),
    path('patrimonio/', views.patrimonio, name='patrimonio'),
    path('departamentos/', views.departamentos, name='departamentos'),
    path('inversiones/', views.inversiones, name='inversiones'),
    path('configuracion/', views.configuracion, name='configuracion'),
    path('calendario/', views.calendario, name='calendario'),
    path('patrimonio/crear-activo/', views.crear_activo, name='crear_activo'),
    path('patrimonio/crear-pasivo/', views.crear_pasivo, name='crear_pasivo'),
    path('configuracion/actualizar-tasas/', update_rates, name='actualizar_tasas'),
    path('configuracion/tomar-snapshot/', take_snapshot, name='tomar_snapshot'),
    path('departamentos/estacionamientos/', views.estacionamientos, name='estacionamientos'),
    path('patrimonio/editar-activo/<int:pk>/', views.editar_activo, name='editar_activo'),
    path('patrimonio/borrar-activo/<int:pk>/', views.borrar_activo, name='borrar_activo'),
    path('patrimonio/editar-pasivo/<int:pk>/', views.editar_pasivo, name='editar_pasivo'),
    path('patrimonio/borrar-pasivo/<int:pk>/', views.borrar_pasivo, name='borrar_pasivo'),
    path('departamentos/crear/', views.crear_departamento, name='crear_departamento'),
    path('departamentos/editar/<int:pk>/', views.editar_departamento, name='editar_departamento'),
    path('departamentos/borrar/<int:pk>/', views.borrar_departamento, name='borrar_departamento'),
    path('inversiones/editar/<int:pk>/', views.editar_inversion, name='editar_inversion'),
    path('inversiones/borrar/<int:pk>/', views.borrar_inversion, name='borrar_inversion'),
    path('gastos/bulk/', views.bulk_gastos, name='bulk_gastos'),
    path('gastos/categoria-stats/<int:cat_pk>/', views.get_category_data, name='categoria_stats'),
    path('configuracion/crear-categoria/', views.crear_categoria, name='crear_categoria'),
    path('configuracion/editar-categoria/<int:pk>/', views.editar_categoria, name='editar_categoria'),
    path('configuracion/borrar-categoria/<int:pk>/', views.borrar_categoria, name='borrar_categoria'),
    path('configuracion/crear-banco/', views.crear_banco, name='crear_banco'),
    path('configuracion/editar-banco/<int:pk>/', views.editar_banco, name='editar_banco'),
    path('configuracion/borrar-banco/<int:pk>/', views.borrar_banco, name='borrar_banco'),
    path('configuracion/crear-producto/', views.crear_producto, name='crear_producto'),
    path('configuracion/editar-producto/<int:pk>/', views.editar_producto, name='editar_producto'),
    path('configuracion/borrar-producto/<int:pk>/', views.borrar_producto, name='borrar_producto'),
    path('calendario/programado/crear/', views.crear_gasto_programado, name='crear_gasto_programado'),
    path('calendario/programado/editar/<int:pk>/', views.editar_gasto_programado, name='editar_gasto_programado'),
    path('calendario/programado/borrar/<int:pk>/', views.borrar_gasto_programado, name='borrar_gasto_programado'),
]
