# Generated by Django 5.1.7 on 2026-03-16 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('CRIPTO', 'Criptomoneda'), ('FONDO_MUTUO', 'Fondo Mutuo'), ('ACCIONES', 'Acciones'), ('BROKERAGE', 'Brokerage Account'), ('PLAZO_FIJO', 'Plazo Fijo'), ('OTRO', 'Otro')], max_length=20)),
                ('monto_clp', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monto_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('porcentaje_cartera', models.DecimalField(decimal_places=2, default=0, help_text='% of total portfolio', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inversión',
                'verbose_name_plural': 'Inversiones',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('monto_clp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_uf', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('valor_dolar', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inversiones.inversion')),
            ],
            options={
                'verbose_name': 'Historial Inversión',
                'verbose_name_plural': 'Historiales Inversiones',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['inversion', '-fecha'], name='inversiones_inversi_dacb46_idx')],
                'unique_together': {('inversion', 'fecha')},
            },
        ),
    ]
