# Generated by Django 6.0.3 on 2026-03-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historialinversion',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='historialinversion',
            name='inversiones_inversi_dacb46_idx',
        ),
        migrations.RemoveField(
            model_name='inversion',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistorialInversion',
        ),
        migrations.DeleteModel(
            name='Inversion',
        ),
    ]
