# Generated by Django 5.1.7 on 2026-03-16 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('departamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('INVERSION', 'Inversión'), ('PRESTAMO_DADO', 'Préstamo Dado'), ('DEPARTAMENTO', 'Departamento'), ('AHORRO', 'Ahorro'), ('OTRO', 'Otro')], max_length=20)),
                ('tipo_liquidez', models.CharField(choices=[('LIQUIDO', 'Líquido'), ('NO_LIQUIDO', 'No Líquido')], default='LIQUIDO', max_length=20)),
                ('monto_clp', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monto_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activo_patrimonial', to='departamentos.departamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MiniSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('PRESTAMO_DADO', 'Préstamo Dado'), ('COBRO_TERCERO', 'Cobro a Tercero'), ('DEUDA', 'Deuda'), ('OTRO', 'Otro')], max_length=20)),
                ('compartible', models.BooleanField(default=False, help_text='Si es True, se pueden ocultar datos sensibles al compartir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minisesiones', to='patrimonio.activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minisesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mini Sesión',
                'verbose_name_plural': 'Mini Sesiones',
                'ordering': ['-fecha', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='LineaMiniSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='patrimonio.minisesion')),
            ],
            options={
                'verbose_name': 'Línea Mini Sesión',
                'verbose_name_plural': 'Líneas Mini Sesión',
                'ordering': ['sesion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Pasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('TDC', 'Tarjeta de Crédito'), ('CREDITO_HIPOTECARIO', 'Crédito Hipotecario'), ('PRESTAMO', 'Préstamo'), ('OTRO', 'Otro')], max_length=25)),
                ('monto_clp', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monto_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasivos', to='configuracion.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pasivo',
                'verbose_name_plural': 'Pasivos',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('activos_total_clp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('activos_total_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pasivos_total_clp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pasivos_total_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('patrimonio_neto_clp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('patrimonio_neto_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('activos_liquidos_clp', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_patrimonio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot Patrimonio',
                'verbose_name_plural': 'Snapshots Patrimonio',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['user', '-fecha'], name='patrimonio__user_id_244b4b_idx')],
                'unique_together': {('user', 'fecha')},
            },
        ),
    ]
