# Generated by Django 6.0.3 on 2026-03-28 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activo',
            options={'ordering': ['horizonte_temporal', 'tipo', 'nombre'], 'verbose_name': 'Activo', 'verbose_name_plural': 'Activos'},
        ),
        migrations.RemoveField(
            model_name='activo',
            name='tipo_liquidez',
        ),
        migrations.AddField(
            model_name='activo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='es_liquido',
            field=models.BooleanField(default=True, help_text='¿Se puede liquidar fácilmente?'),
        ),
        migrations.AddField(
            model_name='activo',
            name='horizonte_temporal',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CORTO_PLAZO', 'Corto Plazo'), ('MEDIANO_PLAZO', 'Mediano Plazo'), ('LARGO_PLAZO', 'Largo Plazo')], default='EFECTIVO', help_text='Horizonte de inversión del activo', max_length=20),
        ),
        migrations.AddField(
            model_name='pasivo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si la deuda sigue vigente'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='tipo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CRIPTO', 'Criptomoneda'), ('FONDO_MUTUO', 'Fondo Mutuo'), ('ACCIONES', 'Acciones'), ('BROKERAGE', 'Brokerage Account'), ('PLAZO_FIJO', 'Plazo Fijo'), ('PRESTAMO_DADO', 'Préstamo Dado'), ('DEPARTAMENTO', 'Departamento'), ('AHORRO', 'Ahorro'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pasivo',
            name='tipo',
            field=models.CharField(choices=[('TDC', 'Tarjeta de Crédito'), ('CREDITO_HIPOTECARIO', 'Crédito Hipotecario'), ('CREDITO_CONSUMO', 'Crédito de Consumo'), ('PRESTAMO', 'Préstamo'), ('OTRO', 'Otro')], max_length=25),
        ),
        migrations.CreateModel(
            name='HistorialActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('monto_clp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_uf', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('valor_dolar', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='patrimonio.activo')),
            ],
            options={
                'verbose_name': 'Historial Activo',
                'verbose_name_plural': 'Historiales Activos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['activo', '-fecha'], name='patrimonio__activo__efe42a_idx')],
                'unique_together': {('activo', 'fecha')},
            },
        ),
    ]
