# Generated by Django 5.1.7 on 2026-03-16 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO_FIJO', 'Gasto Fijo'), ('SUSCRIPCION', 'Suscripción'), ('SEGURO', 'Seguro'), ('TDC', 'Tarjeta de Crédito'), ('COBRO_BANCO', 'Cobro de Banco')], max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banco_defecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_ingresos', to='configuracion.banco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_ingresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría de Ingreso',
                'verbose_name_plural': 'Categorías de Ingreso',
                'ordering': ['tipo', 'orden', 'nombre'],
                'unique_together': {('user', 'nombre', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='GastoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mes_cobro', models.IntegerField(choices=[(1, 'Month 1'), (2, 'Month 2'), (3, 'Month 3'), (4, 'Month 4'), (5, 'Month 5'), (6, 'Month 6'), (7, 'Month 7'), (8, 'Month 8'), (9, 'Month 9'), (10, 'Month 10'), (11, 'Month 11'), (12, 'Month 12')])),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_anuales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto Anual',
                'verbose_name_plural': 'Gastos Anuales',
                'ordering': ['mes_cobro', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GastoTrimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('trimestre', models.IntegerField(choices=[(1, 'Quarter 1'), (2, 'Quarter 2'), (3, 'Quarter 3'), (4, 'Quarter 4')])),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_trimestrales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto Trimestral',
                'verbose_name_plural': 'Gastos Trimestrales',
                'ordering': ['trimestre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('mes', models.IntegerField(choices=[(1, 'Month 1'), (2, 'Month 2'), (3, 'Month 3'), (4, 'Month 4'), (5, 'Month 5'), (6, 'Month 6'), (7, 'Month 7'), (8, 'Month 8'), (9, 'Month 9'), (10, 'Month 10'), (11, 'Month 11'), (12, 'Month 12')])),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneda', models.CharField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar'), ('UF', 'Unidad de Fomento')], default='CLP', max_length=3)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('SUSCRIPCION', 'Suscripción'), ('SEGURO', 'Seguro'), ('TDC', 'Tarjeta de Crédito'), ('COBRO_BANCO', 'Cobro de Banco')], max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='gastos.categoriaingreso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_mensuales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Mensual',
                'verbose_name_plural': 'Registros Mensuales',
                'ordering': ['year', 'mes', 'categoria'],
                'indexes': [models.Index(fields=['user', 'year', 'mes'], name='gastos_regi_user_id_f8e207_idx'), models.Index(fields=['categoria', 'year', 'mes'], name='gastos_regi_categor_a503b2_idx')],
                'unique_together': {('user', 'year', 'mes', 'categoria')},
            },
        ),
    ]
