# Generated by Django 6.0.3 on 2026-03-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaingreso',
            name='contabilizar',
            field=models.BooleanField(default=True, help_text='Si es Falso, no suma al gasto total (ej. ya pagado en TDC)'),
        ),
        migrations.AddField(
            model_name='categoriaingreso',
            name='moneda_defecto',
            field=models.CharField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar'), ('UF', 'Unidad de Fomento')], default='CLP', max_length=3),
        ),
        migrations.AddField(
            model_name='registromensual',
            name='monto_contable_clp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor fijo convertido a CLP al momento de crearse si moneda es USD/UF', max_digits=15, null=True),
        ),
    ]
