# Generated by Django 6.0.3 on 2026-03-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_categoriaingreso_contabilizar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaingreso',
            name='dia_cobro',
            field=models.IntegerField(blank=True, help_text='Día del mes (1-31) en que se cobra/paga esta categoría', null=True),
        ),
    ]
