# Generated by Django 6.0.3 on 2026-03-25 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_gastomensual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastomensual',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gastotrimestral',
            name='user',
        ),
        migrations.CreateModel(
            name='GastoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_inicio', models.DateField(help_text='Fecha base para calcular próximos cobros')),
                ('frecuencia', models.CharField(choices=[('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_programados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto Programado',
                'verbose_name_plural': 'Gastos Programados',
                'ordering': ['fecha_inicio', 'nombre'],
            },
        ),
        migrations.DeleteModel(
            name='GastoAnual',
        ),
        migrations.DeleteModel(
            name='GastoMensual',
        ),
        migrations.DeleteModel(
            name='GastoTrimestral',
        ),
    ]
