# Generated by Django 6.0.3 on 2026-03-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_remove_gastomensual_user_remove_gastotrimestral_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaingreso',
            name='mostrar_en_carga_masiva',
            field=models.BooleanField(default=True, help_text='Si es Falso, se oculta del modal de carga masiva'),
        ),
        migrations.AlterField(
            model_name='categoriaingreso',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO_FIJO', 'Gasto Fijo'), ('SUSCRIPCION', 'Suscripción'), ('SEGURO', 'Seguro'), ('TDC', 'Tarjeta de Crédito'), ('COBRO_BANCO', 'Cobro de Banco'), ('INVERSION', 'Inversión'), ('CREDITO_CONSUMO', 'Crédito de Consumo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registromensual',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('SUSCRIPCION', 'Suscripción'), ('SEGURO', 'Seguro'), ('TDC', 'Tarjeta de Crédito'), ('COBRO_BANCO', 'Cobro de Banco'), ('INVERSION', 'Inversión'), ('CREDITO_CONSUMO', 'Crédito de Consumo')], max_length=20),
        ),
    ]
