# Generated by Django 6.0.3 on 2026-03-28 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_banco_mostrar_en_carga_masiva_banco_notas'),
        ('gastos', '0006_categoriaingreso_mostrar_en_carga_masiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaingreso',
            name='producto_asociado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_vinculada', to='configuracion.producto'),
        ),
    ]
