# Generated by Django 6.0.3 on 2026-03-28 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_producto_tiene_cupo_usd'),
        ('gastos', '0007_categoriaingreso_producto_asociado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaingreso',
            name='producto_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_vinculadas', to='configuracion.producto'),
        ),
    ]
