# Generated by Django 5.1.7 on 2026-03-16 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('piso', models.CharField(max_length=20)),
                ('metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_compra_uf', models.DecimalField(decimal_places=2, help_text='Purchase price in UF', max_digits=10)),
                ('valor_actual_uf', models.DecimalField(decimal_places=2, help_text='Current market value in UF', max_digits=10)),
                ('avaluo_fiscal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tiene_estacionamientos', models.BooleanField(default=False)),
                ('numero_bodegas', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['codigo'],
                'unique_together': {('user', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='CreditoHipotecario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_original_uf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_anual', models.DecimalField(decimal_places=3, help_text='Annual interest rate %', max_digits=5)),
                ('plazo_anos', models.IntegerField(help_text='Loan term in years')),
                ('tipo_tasa', models.CharField(choices=[('FIJA', 'Tasa Fija'), ('SEMIVARIABLE', 'Tasa Semivariable'), ('VARIABLE', 'Tasa Variable')], max_length=15)),
                ('dfl2', models.BooleanField(default=False, help_text='DFL2 tax benefit')),
                ('cuota_uf', models.DecimalField(decimal_places=4, help_text='Monthly payment in UF', max_digits=10)),
                ('saldo_actual_uf', models.DecimalField(decimal_places=2, help_text='Current outstanding balance in UF', max_digits=10)),
                ('cuotas_pagadas', models.IntegerField(default=0)),
                ('cuotas_totales', models.IntegerField()),
                ('cae', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.banco')),
                ('departamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credito_hipotecario', to='departamentos.departamento')),
            ],
            options={
                'verbose_name': 'Crédito Hipotecario',
                'verbose_name_plural': 'Créditos Hipotecarios',
            },
        ),
        migrations.CreateModel(
            name='Arrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio_contrato', models.DateField()),
                ('monto_arriendo_clp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_arriendo_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrendatario', to='departamentos.departamento')),
            ],
            options={
                'verbose_name': 'Arrendatario',
                'verbose_name_plural': 'Arrendatarios',
            },
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('asignado_a_arrendatario', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrendatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estacionamientos', to='departamentos.arrendatario')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacionamientos', to='departamentos.departamento')),
            ],
            options={
                'verbose_name': 'Estacionamiento',
                'verbose_name_plural': 'Estacionamientos',
                'unique_together': {('departamento', 'numero')},
            },
        ),
    ]
