# Generated by Django 6.0.3 on 2026-03-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio del pago', null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='fecha_ultima_cuota',
            field=models.DateField(blank=True, help_text='Fecha de la última cuota', null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='plazo_anos',
            field=models.IntegerField(blank=True, help_text='Plazo en años (opcional si hay fecha_ultima_cuota)', null=True),
        ),
    ]
