# Generated by Django 6.0.3 on 2026-03-28 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_producto_contabilizar_producto_dia_cobro'),
        ('departamentos', '0002_departamento_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditohipotecario',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto de Crédito Hipotecario desde Entidades Financieras', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_hipotecarios', to='configuracion.producto'),
        ),
        migrations.AlterField(
            model_name='creditohipotecario',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuracion.banco'),
        ),
    ]
